/**
 * The approval rationale. SPRINT1.md, Component 4:
 *
 *   "The rationale is generated by a single model call at record creation time. It is not an
 *    agent. It has no tools, no loop, no memory. Its input is the raw facts only ... It must
 *    NOT receive the agent's conversation or the user's original wording."
 *
 * The request the model sees is the frozen system prompt plus renderFacts(facts), and nothing
 * else. The gateway records those exact facts and the exact reply in the audit log under the
 * `rationale` kind, so what the model saw and said is evidence, not a memory.
 *
 * The output is supporting information for a human. It is stored verbatim and never acted on.
 */
import Anthropic from "@anthropic-ai/sdk";

export const DEFAULT_RATIONALE_MODEL = "claude-opus-5";

/** Deliberately short: three sections, under 150 words. */
const MAX_OUTPUT_TOKENS = 1024;

export const RATIONALE_SYSTEM_PROMPT = [
  "You write a short brief for a human approver in an IT identity helpdesk. You receive only the facts of one pending request. You have no other context and must not assume any.",
  "",
  "Write exactly three sections, each with one of these headings on its own line, in this order:",
  "What is being requested",
  "What changes if approved",
  "What is worth checking before approving",
  "",
  "Rules:",
  "- Use only the facts given. Do not invent business context, names, reasons, or urgency.",
  "- Do not recommend approving or rejecting. The approver decides.",
  "- Keep the whole brief under 150 words. Plain text, no markdown, no preamble.",
].join("\n");

/** Raw facts only. Nothing here may come from the conversation. */
export interface RationaleFacts {
  tool: string;
  /** Validated parameters, as the policy engine saw them. */
  params: Record<string, unknown>;
  /** Which rules made this need approval. */
  rules: readonly string[];
  targetUser: string | null;
  targetGroup: { id: string; displayName: string | null } | null;
  requestingUser: string;
}

export interface RationaleResult {
  /** The model's reply, verbatim. */
  text: string;
  /** The model that produced it, as reported by the API. */
  model: string;
  usage: { inputTokens: number; outputTokens: number };
}

export interface RationaleGenerator {
  generate(facts: RationaleFacts): Promise<RationaleResult>;
}

export class RationaleError extends Error {
  override readonly name = "RationaleError";
  constructor(
    /** "api_error:<status>", "stop_reason:<reason>", "empty_response", or "network". */
    readonly code: string,
    message: string,
  ) {
    super(message);
  }
}

export function renderFacts(facts: RationaleFacts): string {
  const group =
    facts.targetGroup === null
      ? "(none)"
      : facts.targetGroup.displayName === null
        ? facts.targetGroup.id
        : `${facts.targetGroup.displayName} (${facts.targetGroup.id})`;
  return [
    `Tool: ${facts.tool}`,
    `Requesting user: ${facts.requestingUser}`,
    `Target user: ${facts.targetUser ?? "(none)"}`,
    `Target group: ${group}`,
    `Rules that require approval: ${facts.rules.length > 0 ? facts.rules.join(", ") : "(none)"}`,
    `Validated parameters: ${JSON.stringify(facts.params)}`,
  ].join("\n");
}

export interface RationaleGeneratorOptions {
  apiKey: string;
  model?: string;
  fetch?: typeof globalThis.fetch;
  /** Milliseconds. This runs inside a tool call, so keep it well under the agent's patience. */
  timeoutMs?: number;
}

export function createRationaleGenerator(options: RationaleGeneratorOptions): RationaleGenerator {
  if (!options.apiKey) throw new Error("ANTHROPIC_API_KEY is required to generate approval rationales");

  const client = new Anthropic({
    apiKey: options.apiKey,
    timeout: options.timeoutMs ?? 60_000,
    maxRetries: 2,
    ...(options.fetch ? { fetch: options.fetch } : {}),
  });
  const model = options.model ?? DEFAULT_RATIONALE_MODEL;

  return {
    async generate(facts) {
      let response: Anthropic.Message;
      try {
        response = await client.messages.create({
          model,
          max_tokens: MAX_OUTPUT_TOKENS,
          system: RATIONALE_SYSTEM_PROMPT,
          messages: [{ role: "user", content: renderFacts(facts) }],
          // A summary of six facts does not need deep reasoning; keep the call cheap and quick.
          output_config: { effort: "medium" },
        });
      } catch (error) {
        if (error instanceof Anthropic.APIError) {
          throw new RationaleError(`api_error:${error.status ?? "unknown"}`, `Rationale request failed (${error.status}): ${error.message}`);
        }
        throw new RationaleError("network", `Rationale request failed: ${error instanceof Error ? error.message : String(error)}`);
      }

      if (response.stop_reason !== "end_turn") {
        throw new RationaleError(`stop_reason:${response.stop_reason}`, `Rationale not completed: stop_reason=${response.stop_reason}`);
      }

      const text = response.content
        .filter((block): block is Anthropic.TextBlock => block.type === "text")
        .map((block) => block.text)
        .join("\n")
        .trim();
      if (text.length === 0) throw new RationaleError("empty_response", "Rationale response contained no text");

      return {
        text,
        model: response.model,
        usage: { inputTokens: response.usage.input_tokens, outputTokens: response.usage.output_tokens },
      };
    },
  };
}
