/**
 * The approval screen. SPRINT1.md, Component 6:
 *
 *   "List of pending approvals, and a detail view with three blocks: raw facts, exactly as
 *    stored; the generated rationale, visually marked as generated; approve and reject
 *    buttons, plus a required decision note field."
 *
 * A null rationale is rendered as an explicit sentence, never as a blank section — a blank
 * one reads as "nothing worth explaining here," which is backwards.
 *
 * decideApproval() only formats what ApprovalWorkflow.decide() already decided; the
 * requester/approver check and the required-note check live there (gateway), not here. This
 * file never re-implements either — it just has to show the refusal honestly when one fires.
 */
import type { ApprovalDecisionInput, ApprovalOutcome, ApprovalRecord } from "@helpdesk/gateway";
import { ApprovalError } from "@helpdesk/gateway";

import { escapeHtml, escapedPre } from "./html.js";

export interface DecideDeps {
  decide: (input: ApprovalDecisionInput) => Promise<ApprovalOutcome>;
}

export type DecideResult = { status: "ok"; outcome: ApprovalOutcome } | { status: "error"; code: string; message: string };

export async function decideApproval(input: ApprovalDecisionInput, deps: DecideDeps): Promise<DecideResult> {
  try {
    const outcome = await deps.decide(input);
    return { status: "ok", outcome };
  } catch (error) {
    if (error instanceof ApprovalError) return { status: "error", code: error.code, message: error.message };
    return { status: "error", code: "unknown", message: error instanceof Error ? error.message : String(error) };
  }
}

// ---------------------------------------------------------------------------

export function renderApprovalsList(approvals: readonly ApprovalRecord[]): string {
  if (approvals.length === 0) {
    return `<h1>Approvals</h1><p>No pending approvals.</p>`;
  }
  const rows = approvals
    .map(
      (a) => `
        <tr>
          <td><a href="/approvals/${escapeHtml(a.id)}">${escapeHtml(a.id)}</a></td>
          <td>${escapeHtml(a.createdAt)}</td>
          <td>${escapeHtml(a.actor)}</td>
          <td>${escapeHtml(a.tool)}</td>
        </tr>`,
    )
    .join("");

  return `
    <h1>Approvals</h1>
    <table>
      <thead><tr><th>Id</th><th>Created</th><th>Requested by</th><th>Tool</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>`;
}

function renderRawFacts(approval: ApprovalRecord): string {
  return `
    <h2>1. Raw facts</h2>
    <p>Exactly as stored — nothing here is generated.</p>
    <table>
      <tr><th>Approval id</th><td>${escapeHtml(approval.id)}</td></tr>
      <tr><th>Request id</th><td>${escapeHtml(approval.requestId)}</td></tr>
      <tr><th>Created</th><td>${escapeHtml(approval.createdAt)}</td></tr>
      <tr><th>Requested by</th><td>${escapeHtml(approval.actor)}</td></tr>
      <tr><th>Tool</th><td>${escapeHtml(approval.tool)}</td></tr>
      <tr><th>Rule(s) requiring approval</th><td>${escapeHtml(approval.rules.join(", "))}</td></tr>
    </table>
    <p>Parameters:</p>
    ${escapedPre(approval.params)}`;
}

function renderRationale(approval: ApprovalRecord): string {
  if (approval.rationale === null) {
    return `
      <h2>2. Rationale</h2>
      <p class="rationale-missing">No rationale was generated for this request.</p>`;
  }
  return `
    <h2>2. Rationale</h2>
    <div class="rationale">
      <div class="rationale-label">Generated by a model — supporting information only, not a decision</div>
      ${escapedPre(approval.rationale)}
    </div>`;
}

function renderDecideResult(result?: DecideResult): string {
  if (!result) return "";
  if (result.status === "error") {
    return `<p class="error">${escapeHtml(result.message)}</p>`;
  }
  const { execution } = result.outcome;
  const executionText =
    execution === null
      ? "Rejected. No change was made."
      : execution.status === "executed"
        ? `Executed.${execution.alreadyMember ? " The user was already a member." : ""}`
        : `Approved, but execution failed: ${execution.message}`;
  return `<p class="ok">${escapeHtml(executionText)}</p>`;
}

function renderDecideForm(approval: ApprovalRecord): string {
  return `
    <form method="post" action="/approvals/${escapeHtml(approval.id)}/decide">
      <label for="decidedBy">Your identity (UPN) — must not match the requester</label>
      <input type="text" id="decidedBy" name="decidedBy" placeholder="it.manager@contoso.com" required>

      <label for="note">Decision note (required to approve or reject)</label>
      <textarea id="note" name="note" required></textarea>

      <button type="submit" name="decision" value="approved">Approve</button>
      <button type="submit" name="decision" value="rejected">Reject</button>
    </form>`;
}

function renderDecided(approval: ApprovalRecord): string {
  return `
    <table>
      <tr><th>Status</th><td>${escapeHtml(approval.status)}</td></tr>
      <tr><th>Decided by</th><td>${escapeHtml(approval.decidedBy)}</td></tr>
      <tr><th>Decided at</th><td>${escapeHtml(approval.decidedAt)}</td></tr>
      <tr><th>Decision note</th><td>${escapeHtml(approval.decisionNote)}</td></tr>
    </table>`;
}

export function renderApprovalDetail(approval: ApprovalRecord, decideResult?: DecideResult): string {
  return `
    <h1>Approval ${escapeHtml(approval.id)}</h1>
    ${renderDecideResult(decideResult)}
    ${renderRawFacts(approval)}
    ${renderRationale(approval)}
    <h2>3. Decision</h2>
    ${approval.status === "pending" ? renderDecideForm(approval) : renderDecided(approval)}`;
}
